version: "3.8"

services:
  backend-fastapi:
    container_name: api-diffusion
    build:
      context: ./api/
      dockerfile: Dockerfile.cpu
    ports:
      - 8080:8080
    restart: unless-stopped
    # networks:
    #   - deploy_network
    # deploy:
    #   resources:
    #       reservations:
    #           devices:
    #             - driver: nvidia
    #               device_ids: ['0']
    #               capabilities: [gpu]

#   frontend-streamlit:
#     build: ./streamlit
#     ports:
#       - 8501:8501
#     restart: unless-stopped
#     networks:
#       - deploy_network
#     container_name: frontend-streamlit


# networks:
#   deploy_network:
#     driver: bridge